server:
    port: 8080

#spring:
#    datasource:
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/uos25
#        username: uos25
#        password: Enlwu5413!
#    jpa:
#        hibernate:
#            ddl-auto: create-drop
#        generate-ddl: true
#        properties:
#            hibernate:
#                default_batch_fetch_size: 1000
#                show_sql: true
#                format_sql: true

## H2 Database
spring:
    datasource:
        url: jdbc:h2:tcp://localhost/~/UOS25-test
        username: sa
        password:
        driver-class-name: org.h2.Driver

    jpa:
        hibernate:
            ddl-auto: update
        properties:
          hibernate:
              format_sql: true
              show_sql: true

logging.level:
    org.hibernate.SQL: debug



jwt:
    refresh:
        secret: bee329d3078de4938621792663ce34b548966df3c4047b5cbfe1f5791e649e1d
        expiration: 1209600000

    access:
        secret: 038609c7fe2c9142f3d74cfb710469eec3d74450756f273306e1321cedd2a6a3
        expiration: 3600000

springdoc:
    swagger-ui:
        path: /swagger/swagger-ui.html
        operationsSorter: method
        disable-swagger-default-url: true
        display-request-duration: true
    api-docs:
        path: /swagger/api-docs
    show-actuator: true
    default-consumes-media-type: application/json
    default-produces-media-type: application/json
