server:
    port: 8080

spring:
    datasource:
        driver-class-name: oracle.jdbc.driver.OracleDriver
        url: jdbc:oracle:thin:@localhost:1521:XE
        username: ${DATABASE_USERNAME}
        password: ${DATABASE_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: create
        generate-ddl: true
        properties:
            hibernate:
                default_batch_fetch_size: 1000
                show_sql: true
                format_sql: true

logging.level:
    org.hibernate.SQL: debug

springdoc:
    swagger-ui:
        path: /
        operationsSorter: method
        disable-swagger-default-url: true
        display-request-duration: true
    default-consumes-media-type: application/json
    default-produces-media-type: application/json
